# permissions for end users to view apichecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicheck-viewer-role
rules:
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - apichecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - apichecks/status
  verbs:
  - get
