# permissions for end users to view alertchannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertchannel-viewer-role
rules:
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - alertchannels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - alertchannels/status
  verbs:
  - get
