# permissions for end users to edit alertchannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertchannel-editor-role
rules:
- apiGroups:
  - checkly.checklyhq.com
  resources:
  - alertchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checkly.checklyhq.com
  resources:
  - alertchannels/status
  verbs:
  - get
