# permissions for end users to view groups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: group-viewer-role
rules:
- apiGroups:
  - checkly.imgarena.com
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - checkly.imgarena.com
  resources:
  - groups/status
  verbs:
  - get
