---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - alertchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - alertchannels/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - alertchannels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - apichecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - apichecks/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - apichecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - groups/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.checklyhq.com
  resources:
  - groups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
