name: Build and test Go
on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USE_EXISTING_CLUSTER: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Download operatork-sdk
        env:
          OPERATOR_SDK_VERSION: "v1.18.1" # The operator-sdk version to download (if necessary) and use.
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/${OPERATORK_SDK_VERSION}
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

      - name: Start kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: "v0.12.0"

      - name: Test code
        env:
          USE_EXISTING_CLUSTER: true
        run: |
          make test

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker container
        env:
          DOCKER_TAG: ${{ github.sha }}
          DOCKER_CONTAINER: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          docker build -t ${DOCKER_CONTAINER,,}:${DOCKER_TAG} .
        # ${var,,} makes var all lowercase
